services:
  app:
    image: bloglist-frontend
    build:
      context: ./bloglist-frontend
      dockerfile: Dockerfile
    container_name: bloglist-frontend
  backend:
    image: bloglist-express-server
    build:
      context: ./bloglist-backend
      dockerfile: Dockerfile
    container_name: bloglist-backend
    environment:
      - MONGODB_URI=${MONGODB_URI}
      - PORT=${PORT}
      - SECRET=${SECRET}
  nginx:
    image: nginx:1.20.1
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 8080:80
    container_name: reverse-proxy-bloglist
    depends_on:
      - app
      - backend